### ISSUE TITLE
Test e-imunisasi 

### ISSUE THREAD

**Issue by peltops** [peltops/e-imunisasi#122]
Prerequisites:
1. Use release 2.1.1 from Nov 13, 2023

Steps:
1. Install e-imunisasi from Play Store
2. Create User
3. Login

Expected result:
1. e-imunisasi is installed
2. User is created successfully
3. Login is successful

**Comment by peltops** [comment]
e-imunisasi is installed - PASS

**Comment by Lailabalqiss** [comment]
1. e-imunisasi is installed ✅
2. User is created successfully ✅
3. Login is successful ✅

**Comment by Lailabalqiss** [comment]
![WhatsApp Image 2023-11-13 at 19 44 08_53a46680](https://github.com/peltops/e-imunisasi/assets/148629238/09c2629b-d02c-4ddf-aabf-f1a2835bde01)
![WhatsApp Image 2023-11-13 at 19 44 09_1259c0fd](https://github.com/peltops/e-imunisasi/assets/148629238/4511439b-1791-47d6-b708-5a364532d7ec)
![WhatsApp Image 2023-11-13 at 19 44 09_19e54f41](https://github.com/peltops/e-imunisasi/assets/148629238/b5bc58b9-f173-4a00-bbbe-091b53b2bbc9)
