### ISSUE TITLE
Update Infografik

### ISSUE THREAD

**Issue by R-Nazzla** [peltops/e-imunisasi#18]
infografik lama, disesuaikan dengan saran Pak Yudha

![infografik_lama](https://user-images.githubusercontent.com/71178609/108196944-9462aa00-70ce-11eb-9dc1-79ced21c668d.jpeg)

**Comment by peltops** [comment]
- Content masih valid.
- Upload gambar yg high-resolution

**Comment by peltops** [comment]
- Fitur imunisasi@home dimasukkan ke dalam fitur event sebagai pilihan.
- Fitur imunisasi@home dihilangkan dari infografis
- Tambahan di infografis: user bisa memilih lokasi pelaksanaan imunisasi

**Comment by R-Nazzla** [comment]
![edit-22-03-2021](https://user-images.githubusercontent.com/71178609/109726207-222aa480-7b67-11eb-823a-fa9672b6014f.jpg)
