### ISSUE TITLE
review UI list janji eimunisasi

### ISSUE THREAD

**Issue by rfaturriza** [peltops/e-imunisasi#199]

**Comment by rfaturriza** [comment]
![Image](https://github.com/user-attachments/assets/341d7bf9-65cf-4ffb-aeb3-b4a1bdfa9fa6)

**Comment by rfaturriza** [comment]
![Image](https://github.com/user-attachments/assets/3fd110d0-53c5-49fc-8ef7-9bf94c520a76)

**Comment by faisaladnanpeltops** [comment]
Update:
- add 2 types of sorting: by date, and by name
- the default sorting is by date

**Comment by faisaladnanpeltops** [comment]
@rfaturriza , please see above update. Is the implementation feasible?

**Comment by rfaturriza** [comment]
Yes, it is feasible. I'll do it

**Comment by rfaturriza** [comment]
> [@rfaturriza](https://github.com/rfaturriza) , please see above update. Is the implementation feasible?

Yes, it is feasible. I'll do it
