### ISSUE TITLE
Konten Informasi dan Grafik

### ISSUE THREAD

**Issue by R-Nazzla** [peltops/e-imunisasi#24]

**Comment by R-Nazzla** [comment]
![boy](https://user-images.githubusercontent.com/71178609/112141243-4be95100-8b92-11eb-8320-c336b23f8bd3.jpg)
![girl](https://user-images.githubusercontent.com/71178609/112141255-4f7cd800-8b92-11eb-848a-4fa14cc454cb.jpg)

**Comment by R-Nazzla** [comment]
![jadwal imunisasi](https://user-images.githubusercontent.com/71178609/112141547-a387bc80-8b92-11eb-9710-ce489cb6b911.jpg)

**Comment by rfaturriza** [comment]
update informasi mengenai mengapa imunisasinya bertahap, apa manfaat dari tiap tahapan dan efek samping dari tiap tahap imunisasi serta efek sampingnya berbahaya atau normal.

**Comment by R-Nazzla** [comment]
Berdasarkan Peraturan Menteri Kesehatan Republik Indonesia No.42 Tahun 2013 dan No.12 Tahun 2017 tentang penyelenggaraan imunisasi. Ada lima jenis imunisasi wajib ini diberikan sesuai usia anak dan jadwal yang telah ditetapkan oleh pemerintah, serta tentunya berdasarkan pertimbangan dokter. Kelima jenis imunisasi tersebut adalah:
 
1. Imunisasi hepatitis B
Imunisasi hepatitis B bertujuan untuk mencegah penyakit hepatitis B, yaitu infeksi hati yang dapat menimbulkan komplikasi berbahaya, seperti sirosis dan kanker hati. Jenis vaksin yang digunakan adalah vaksin hepatitis B.
 
Vaksin tersebut diberikan pada bayi sebanyak 4 kali. Pemberian pertama dilakukan segera setelah bayi lahir atau paling lambat 12 jam setelah kelahiran. Lalu, vaksin kembali diberikan secara berturut-turut pada usia 2, 3, dan 4 bulan.
 
Jika bayi terlahir dari ibu yang terjangkit hepatitis B, maka pemberian imunisasi hepatitis B pada bayi wajib diberikan dalam waktu paling lambat 12 jam setelah lahir. Bayi tersebut juga perlu mendapatkan suntikan imunoglobulin hepatitis B (HBIG) untuk menghasilkan kekebalan tubuh terhadap virus hepatitis B dalam waktu cepat.
 
2. Imunisasi Polio
 
Polio adalah penyakit menular akibat infeksi virus yang menyerang sistem saraf di otak dan saraf tulang belakang. Pada kasus yang parah, polio dapat menyebabkan sesak napas, meningitis, kelumpuhan, hingga kematian. Nah, imunisasi polio bertujuan untuk mencegah anak tertular penyakit tersebut.
 
Di Indonesia, jenis vaksin polio yang umumnya digunakan adalah vaksin polio tetes (oral), namun vaksin polio juga ada yang tersedia dalam bentuk suntikan.
 
Vaksin polio tetes diberikan 4 kali, yaitu saat bayi baru lahir atau paling lambat saat usianya 1 bulan. Selanjutnya, vaksin diberikan secara berturut-turut di usia 2 bulan, 3 bulan, dan 4 bulan. Sementara, vaksin polio suntik diberikan 1 kali, yaitu pada usia 4 bulan.
 
3. Imunisasi BCG
Imunisasi ini bertujuan untuk melindungi tubuh dari kuman penyebab penyakit tuberkulosis atau TB. TB adalah penyakit menular berbahaya yang dapat menyerang saluran pernapasan, tulang, otot, kulit, kelenjar getah bening, otak, saluran cerna, dan ginjal.
 
Imunisasi BCG termasuk dalam daftar imunisasi wajib di Indonesia, karena Indonesia masih memiliki angka kasus TB yang tinggi. Imunisasi BCG hanya dilakukan 1 kali dan diberikan pada bayi di usia 2 atau 3 bulan. Imunisasi BCG diberikan melalui suntikan pada kulit bayi.
 
4. Imunisasi Campak
Imunisasi campak diberikan sebagai langkah pencegahan terhadap penyakit campak berat yang dapat menyebabkan pneumonia, diare, dan radang otak (ensefalitis). Imunisasi campak diberikan sebanyak 3 kali, yaitu saat anak berusia 9 bulan, 18 bulan, dan 6 tahun.
 
Jika anak diberikan vaksin MR/MMR di usia 15 bulan, maka pemberian imunisasi campak ulang di usia 18 bulan tidak diperlukan. Hal ini karena vaksin MR atau MMR tersebut sudah mengandung vaksin campak.
 
5. Imunisasi DPT-HB-HiB
Imunisasi DPT-HB-HiB dapat memberikan perlindungan dan pencegahan terhadap 6 penyakit sekaligus, yaitu difteri, pertusis (batuk rejan), tetanus, hepatitis B, pneumonia, dan meningitis (radang otak).
 
Imunisasi wajib ini diberikan sebanyak 4 kali dengan jadwal pemberian berturut-turut pada bayi di usia 2 bulan, 3 bulan, 4 bulan, dan dosis pemberian terakhir ketika usia anak 18 bulan.

**Comment by R-Nazzla** [comment]
![Jadwal-Imunisasi-Anak-2020-Rekomendasi-IDAI](https://user-images.githubusercontent.com/71178609/113239837-5d042300-9260-11eb-86c8-05a8dcfdc342.jpg)

**Comment by R-Nazzla** [comment]
[Jenis Vaksin dan manfaat.docx](https://github.com/peltops/e-imunisasi/files/6241208/Jenis.Vaksin.dan.manfaat.docx)

**Comment by R-Nazzla** [comment]
[Jenis Vaksin Manfaat Efek Samping.docx](https://github.com/peltops/e-imunisasi/files/6241238/Jenis.Vaksin.Manfaat.Efek.Samping.docx)

**Comment by peltops** [comment]
- content dibuatkan menjadi tulisan berseri di digital.peltops.com
