### ISSUE TITLE
Daftar potensial Bidan

### ISSUE THREAD

**Issue by peltops** [peltops/e-imunisasi#26]

**Comment by R-Nazzla** [comment]
Daftar Nakes Potensial untuk uji coba App
Ada 2-3 bidan
Lulusan farmasi
Bidan magang

Ketentuan dan persyaratan terkait ID. Kesediaan

**Comment by Fairusfairus** [comment]
bidan di langsa
1. bidan aton
   sedang tidak aktif bekerja sebagai bidan di rumkit
   tapi bisa bantu sebagai nakes di app e-imunisasi
2. bidan ina
   bidan senior (belom di telp)
3. ayu (farmasi)
   baru selesai sekolah dan siap membantu peltops
4. Dosen Keperawatan
   Bisa membantu mencarikan bidan atau perawat yang magang

bidan di aceh timur
1. bidan epi
   bidan senior (belum di hubungi)

**Comment by Fairusfairus** [comment]
5. bidan devi
   bidan bakti di puskesmas
