### ISSUE TITLE
Riset cara membuat multi language di flutter

### ISSUE THREAD

**Issue by rfaturriza** [peltops/e-imunisasi#29]

**Comment by rfaturriza** [comment]
Easy Localization (Published Feb 20, 2021)
Video tutorial: https://youtu.be/cposNqIsyAY
Code on GitHub link: https://github.com/YazeedAlKhalaf/easy_localization_example
Package: https://pub.dev/packages/easy_localization

**Comment by peltops** [comment]
- cek mengapa kode bahasa aceh termasuk iso 639-2 dan bukan 639-1
- bisa dilanjutkan dengan implementasi

**Comment by peltops** [comment]
- membuat presentasi cara menerjemahkan kata atau kalimat

**Comment by rfaturriza** [comment]
implementasi:
https://github.com/rfaturriza/multilanguage_flutter_example

langkah mudah untuk membuat database bahasa:
https://www.electronjs.org/apps/i18n-manager
