### ISSUE TITLE
Riset buat language code baru di Flutter

### ISSUE THREAD

**Issue by rfaturriza** [peltops/e-imunisasi#32]

**Comment by R-Nazzla** [comment]
https://api.flutter.dev/flutter/dart-ui/Locale-class.html
https://flutter.dev/docs/development/accessibility-and-localization/internationalization

**Comment by rfaturriza** [comment]
**bahasa yang didukung material**
https://api.flutter.dev/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html

**hasil untuk implementasi dari** 
https://flutter.dev/docs/development/accessibility-and-localization/internationalization
hasilnya sama  error pada material widget

Kesimpulan dari saya:
jadi sepertinya jika ingin mengimplementasikan bahasa aceh, manipulasikan dengan menggunakan kode bahasa lain.

**Comment by rfaturriza** [comment]
Tes implementasi bahsa aceh pakai catalan dari language code yang support.
