### ISSUE TITLE
wireframe aplikasi berbasis material disain

### ISSUE THREAD

**Issue by Fairusfairus** [peltops/e-imunisasi#33]

**Comment by Fairusfairus** [comment]
1. mengganti menu layanan dengan vaksinasi di halaman utama
2. di menu daftar nakes tampilan nama, foto, kalender, tombol pilih hanya satu di bawah, tombol pencarian diatas 
3. vaksinasi dirumah ditunda dulu
![image](https://user-images.githubusercontent.com/69728579/117535412-d17c6f80-b01f-11eb-9490-77e2052d1cbf.png)
 4. tenaga kesehatan dan klinik pindah ke kontak pada menu utama
 
![image](https://user-images.githubusercontent.com/69728579/117535534-6e3f0d00-b020-11eb-86b3-c58fbbaa04fb.png)

**Comment by R-Nazzla** [comment]
![WhatsApp Image 2021-05-08 at 17 11 03](https://user-images.githubusercontent.com/71178609/119252754-b30b8d80-bb62-11eb-89e6-0911f84f58f2.jpeg)

**Comment by R-Nazzla** [comment]
Halaman onboarding
