### ISSUE TITLE
membuat menu pesan dan bantuan

### ISSUE THREAD

**Issue by rfaturriza** [peltops/e-imunisasi#50]

**Comment by Fairusfairus** [comment]
1. di menu pesan (untuk nakes) belum selesai
2. lambang titik di kalender diganti dgan lambang angka

**Comment by Fairusfairus** [comment]
3. jadwal imunisasi otomatis

**Comment by rfaturriza** [comment]
[jadwalimunisasi.xlsx](https://github.com/peltops/e-imunisasi/files/6835834/jadwalimunisasi.xlsx)
Mungkin bisa di cek dulu apa betul jadwalnya seperti ini?
