### ISSUE TITLE
Feedback dan Ide Nazla 

### ISSUE THREAD

**Issue by peltops** [peltops/e-imunisasi#8]
Penerima manfaat app: individu berusia 0-24 bulan
Pengguna 1. Peserta adalah: a. personal anak, atau b. kepala keluarga
Pengguna 2. Tenaga Kesehatan (Nakes)
Admin?

Tujuan app
-membantu penerima manfaat untuk memperoleh vaksinasi tepat waktu 
-membantu penerima manfaat untuk terhubung dengan Tenaga Kesehatan dan menerima layanan kesehatan terdekat
-membantu user/penerima manfaat memiliki data riwayat imunisasi
-terbangunnya database yang memudahkan tenaga kesehatan dalam memberikan layanan ke masyarakat

Registrasi: 2 User 
Verifikasi sementara berdasarkan ID Tenaga Kesehatan

Personal data : Bagi Tenaga Kesehatan tersedia pilihan menyimpan lokasi tempat dinas dan klinik pribadi.
Untuk sementara, prioritaskan kemudahan bagi Tenaga Kesehatan mengisi personal data dan memverifikasi ID nya, sehingga jika database Tenaga Kesehatan yang "Verified" sudah terbangun, maka kepercayaan pengguna meningkat. Selanjutnya Nakes dapat mengatur event di tempat dinasnya. Untuk fasilitas "imunisasi di rumah saja" sementara dapat memanfaatkan koneksi dengan akun pribadi Tenaga Kesehatan

Set alarm : Supaya lebih ringkas, sebaiknya dikurangi saja, karena sudah tersedia "notifikasi" sebagai alarm pengingat jadwal imunisasi yang telah diatur pada saat mengisi event di kalender yang juga terkoneksi secara otomatis dengan usia anak.

Data dan Informasi Pertumbuhan Anak
terdiri dari:
~Tabel
~Grafik 
~Interpretasi

~ Tabel, berisi data vaksinasi, berat badan, tinggi badan, lingkar kepala, dll

~Grafik
terdiri dari 2 jenis
a. Grafik referensi (WHO atau IDAI)
![image](https://user-images.githubusercontent.com/71178609/107855155-99291480-6dd5-11eb-9890-752567260045.png)
(belum ketemu rumus grafik referensi dan WHO atau IDAI, jadi sementara pakai rumus ini, nanti diperbaiki lagi kurvanya biar lebih halus)
b. Grafik aktual, terbentuk berdasarkan data anak dan overlap dengan grafik referensi, contoh
![image](https://user-images.githubusercontent.com/71178609/107855384-c924e780-6dd6-11eb-97ae-116356481ea4.png)

~Interpretasi, berisi cara membaca grafik, atau penjelasan tentang kondisi penerima manfaat dan saran 

Informasi berisi tentang:
-Deskripsi masing-masing jenis vaksin

Tambahan: Fitur chat : konsultasi dengan Nakes / admin

**Comment by rfaturriza** [comment]
Terima kasih kak nazla atas masukannya.

**Comment by R-Nazzla** [comment]
Ok sama2..

**Comment by Fairusfairus** [comment]
bagus sekali masukannya naz...
itu rumus naz buat sendiri??
oya mengenai fitur set alarm apa kita hilangkan?

**Comment by R-Nazzla** [comment]
Iya grafiknya buat sendiri, datanya diekstrak dari grafik IDAI, digambar ulang dengan excel dan didapat trendline logaritmiknya. 

Untuk set alarm, bisa aja kak, tapi waktunya ga perlu di set manual seperti "ALARM" di JAM HP.  
Menurut saya di tahap  pengembangan awal ini sudah cukup seperti Event yang tersedia di Kalender, Karena Notifnya nanti masuk ke "Newsfeed" Penerima Manfaat.

**Comment by R-Nazzla** [comment]
![kurva growth](https://user-images.githubusercontent.com/71178609/108616997-8ca14f00-73c7-11eb-8845-0ccfd9730f13.jpg)

**Comment by R-Nazzla** [comment]
![kurva growth](https://user-images.githubusercontent.com/71178609/108617042-dee27000-73c7-11eb-8877-69d148fd5ba7.jpg)

**Comment by R-Nazzla** [comment]
![kurva growth](https://user-images.githubusercontent.com/71178609/108617062-1e10c100-73c8-11eb-89ce-45546fd64d40.jpg)

**Comment by R-Nazzla** [comment]
![tabel](https://user-images.githubusercontent.com/71178609/108957403-41d14280-7626-11eb-90c3-6ce35a27b0fa.jpg)

**Comment by R-Nazzla** [comment]
![user](https://user-images.githubusercontent.com/71178609/108957600-9ffe2580-7626-11eb-9804-da88e16bdf4e.jpg)

**Comment by R-Nazzla** [comment]
![tuj app](https://user-images.githubusercontent.com/71178609/108959475-4cd9a200-7629-11eb-94bd-aa5bedac3c21.jpg)

**Comment by R-Nazzla** [comment]
NEWSFEED 
![newsfeed](https://user-images.githubusercontent.com/71178609/108959635-85797b80-7629-11eb-808e-73663b56a573.jpg)

EVENTS
![event](https://user-images.githubusercontent.com/71178609/108959877-e903a900-7629-11eb-911a-cd319e54af7e.jpg)

FORUM
![forum](https://user-images.githubusercontent.com/71178609/108959751-b35ec000-7629-11eb-8b23-83c0e6f616d6.jpg)

**Comment by R-Nazzla** [comment]
NEWSFEED
![newsfeed](https://user-images.githubusercontent.com/71178609/108960190-5f081000-762a-11eb-9c42-10d00597bdef.jpg)

EVENTS
![event](https://user-images.githubusercontent.com/71178609/108960210-65968780-762a-11eb-8685-6f7e4cb2b342.jpg)

FORUM
![forum](https://user-images.githubusercontent.com/71178609/108960234-6f1fef80-762a-11eb-87b7-d76e5ad563d3.jpg)

**Comment by R-Nazzla** [comment]
event
-pilihan membuat jadwal sesuai jadwal di tempat dinas, dan imunisasi at home dgn metode berbayar

forum
-tanya jawab dengan pakar

icon search 
-pencarian  tentang tema tertentu
